on: [push, pull_request]

name: Go
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Download Go dependencies
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go mod download
    - name: Test
      run: go test -count=1 ./...
    - name: Test with -race
      run: go test -race -count=1 ./...
    - name: gofmt check
      run: diff <(echo -n) <(gofmt -d .)
      if: matrix.platform == 'ubuntu-latest'
    - name: staticcheck.io
      if: matrix.platform == 'ubuntu-latest'
      # https://github.com/actions/setup-go/issues/14
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u honnef.co/go/tools/cmd/staticcheck
        staticcheck -checks all .
        # ignore should not use ALL_CAPS in Go names in internal/
        staticcheck -checks all,-ST1003 ./internal/...
